_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix: monitor/health

evt_api_home:
    resource: EVT\ApiBundle\Controller\DefaultController
    prefix:   /
    schemes:  [https]

evt_api:
    resource: "@EVTApiBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api/
    schemes:  [https]
