EVT\CoreDomainBundle\Entity\GenericUser:
    repositoryClass: EVT\CoreDomainBundle\Repository\UserRepository
    type: entity
    table: generic_user
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
        email_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        name:
            type: string
            nullable: true
            length: 60
            fixed: false
            comment: ''
        surnames:
            type: string
            nullable: true
            length: 60
            fixed: false
            comment: ''
        phone:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
    manyToMany:
        provider:
            targetEntity: Provider
            cascade: {  }
            mappedBy: genericUser
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
