EVT\CoreDomainBundle\Entity\LeadInformation:
    type: entity
    table: lead_information
    indexes:
        fk_lead_information_lead_idx:
            columns:
                - lead_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        key:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        value:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        lead:
            targetEntity: Lead
            cascade: {  }
            mappedBy: null
            inversedBy: lead_information
            joinColumns:
                lead_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
