EVT\CoreDomainBundle\Entity\Vertical:
    repositoryClass: EVT\CoreDomainBundle\Repository\VerticalRepository
    type: entity
    table: vertical
    id:
        domain:
            type: string
            nullable: false
            unsigned: false
            length: 45
            id: true
            generator:
                strategy: none
    fields:
        lang:
            type: string
            nullable: false
            length: 5
            fixed: false
            comment: ''
        timezone:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
