evt_api_lead:
    resource: EVT\ApiBundle\Controller\LeadController
    type: rest
evt_api_manager:
    resource: EVT\ApiBundle\Controller\ManagerController
    type: rest
evt_api_provider:
    resource: EVT\ApiBundle\Controller\ProviderController 
    type: rest
